eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8081
  servlet:
    context-path:

spring:
  application:
    name: cinema-api-service

datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/movie_db1?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect